// SOCCER
export const SPORTS_POSITIONS_SOCCER = {
  SOCCER_GOALKEEPER: 'Goleiro',
  SOCCER_DEFENDER: 'Zagueiro',
  SOCCER_DEFENSIVE_SIDE_BACK: 'Lateral-defensivo',
  SOCCER_MIDFIELDER: 'Meio-campo',
  SOCCER_FORWARD: 'Atacante',
};

export const SPORTS_POSITIONS_SOCCER_OPTIONS = [
  {
    key: '1',
    value: SPORTS_POSITIONS_SOCCER.SOCCER_GOALKEEPER,
  },
  {
    key: '2',
    value: SPORTS_POSITIONS_SOCCER.SOCCER_DEFENDER,
  },
  {
    key: '3',
    value: SPORTS_POSITIONS_SOCCER.SOCCER_DEFENSIVE_SIDE_BACK,
  },
  {
    key: '4',
    value: SPORTS_POSITIONS_SOCCER.SOCCER_MIDFIELDER,
  },
  {
    key: '4',
    value: SPORTS_POSITIONS_SOCCER.SOCCER_FORWARD,
  },
];

// VOLLEYBALL
export const SPORTS_POSITIONS_VOLLEYBALL = {
  VOLLEYBALL_SETTER: 'Levantador',
  VOLLEYBALL_SPOKE: 'Ponteiro',
  VOLLEYBALL_LIBERO: 'Líbero',
  VOLLEYBALL_MIDDLE_BLOCKER: 'Central',
  VOLLEYBALL_OPPOSITE: 'Oposto',
};

export const SPORTS_POSITIONS_VOLLEYBALL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_POSITIONS_VOLLEYBALL.VOLLEYBALL_SETTER,
  },
  {
    key: '2',
    value: SPORTS_POSITIONS_VOLLEYBALL.VOLLEYBALL_SPOKE,
  },
  {
    key: '3',
    value: SPORTS_POSITIONS_VOLLEYBALL.VOLLEYBALL_LIBERO,
  },
  {
    key: '4',
    value: SPORTS_POSITIONS_VOLLEYBALL.VOLLEYBALL_MIDDLE_BLOCKER,
  },
  {
    key: '5',
    value: SPORTS_POSITIONS_VOLLEYBALL.VOLLEYBALL_OPPOSITE,
  },
];

// BASKETBALL
export const SPORTS_POSITIONS_BASKETBALL = {
  BASKETBALL_POINT_GUARD: 'Armador',
  BASKETBALL_SHOOTING_GUARD: 'Ala-armador',
  BASKETBALL_SMALL_FORWARD: 'Ala',
  BASKETBALL_POWER_FORWARD: 'Ala-pivô',
  BASKETBALL_CENTER: 'Pivô',
};

export const SPORTS_POSITIONS_BASKETBALL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_POSITIONS_BASKETBALL.BASKETBALL_POINT_GUARD,
  },
  {
    key: '2',
    value: SPORTS_POSITIONS_BASKETBALL.BASKETBALL_SHOOTING_GUARD,
  },
  {
    key: '3',
    value: SPORTS_POSITIONS_BASKETBALL.BASKETBALL_SMALL_FORWARD,
  },
  {
    key: '4',
    value: SPORTS_POSITIONS_BASKETBALL.BASKETBALL_POWER_FORWARD,
  },
  {
    key: '5',
    value: SPORTS_POSITIONS_BASKETBALL.BASKETBALL_CENTER,
  },
];

// HANDBALL
export const SPORTS_POSITIONS_HANDBALL = {
  HANDBALL_GOALKEEPER: 'Goleiro',
  HANDBALL_CENTRAL_BACK: 'Meia defensivo',
  HANDBALL_WING: 'Ponta',
  HANDBALL_HALF: 'Meia',
  HANDBALL_PIVOT: 'Pivô',
};

export const SPORTS_POSITIONS_HANDBALL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_POSITIONS_HANDBALL.HANDBALL_GOALKEEPER,
  },
  {
    key: '2',
    value: SPORTS_POSITIONS_HANDBALL.HANDBALL_CENTRAL_BACK,
  },
  {
    key: '3',
    value: SPORTS_POSITIONS_HANDBALL.HANDBALL_WING,
  },
  {
    key: '4',
    value: SPORTS_POSITIONS_HANDBALL.HANDBALL_HALF,
  },
  {
    key: '5',
    value: SPORTS_POSITIONS_HANDBALL.HANDBALL_PIVOT,
  },
];

export const SPORTS_POSITIONS = {
  VOLLEYBALL: SPORTS_POSITIONS_VOLLEYBALL_OPTIONS,
  BASKETBALL: SPORTS_POSITIONS_BASKETBALL_OPTIONS,
  SOCCER: SPORTS_POSITIONS_SOCCER_OPTIONS,
  HANDBALL: SPORTS_POSITIONS_HANDBALL_OPTIONS,
};
