export const SPORTS_MODALITIES_SOCCER = {
  FUTSAL: 'Futsal',
  FOOTBALL_SOCIETY: 'Society',
};

export const SPORTS_MODALITIES_SOCCER_OPTIONS = [
  {
    key: '1',
    value: SPORTS_MODALITIES_SOCCER.FUTSAL,
    apiValue: 'FUTSAL',
  },
  {
    key: '2',
    value: SPORTS_MODALITIES_SOCCER.FOOTBALL_SOCIETY,
    apiValue: 'FOOTBALL_SOCIETY',
  },
];

export const SPORTS_MODALITIES_VOLLEYBALL = {
  INDOOR_VOLLEYBALL: 'Vôlei de Quadra',
  BEACH_VOLLEYBALL: 'Vôlei de Praia',
  FOOTVOLLEY: 'Futevôlei',
};

export const SPORTS_MODALITIES_VOLLEYBALL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_MODALITIES_VOLLEYBALL.INDOOR_VOLLEYBALL,
    apiValue: 'INDOOR_VOLLEYBALL',
  },
  {
    key: '2',
    value: SPORTS_MODALITIES_VOLLEYBALL.BEACH_VOLLEYBALL,
    apiValue: 'BEACH_VOLLEYBALL',
  },
  {
    key: '3',
    value: SPORTS_MODALITIES_VOLLEYBALL.FOOTVOLLEY,
    apiValue: 'FOOTVOLLEY',
  },
];

export const SPORTS_MODALITIES_BASKETBALL = {
  BASKETBALL_3X3: 'Basquete 3x3',
  BASKETBALL_5X5: 'Basquete 5x5',
};

export const SPORTS_MODALITIES_BASKETBALL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_MODALITIES_BASKETBALL.BASKETBALL_3X3,
    apiValue: 'BASKETBALL_3X3',
  },
  {
    key: '2',
    value: SPORTS_MODALITIES_BASKETBALL.BASKETBALL_5X5,
    apiValue: 'BASKETBALL_5X5',
  },
];

export const SPORTS_MODALITIES_TENNIS = {
  TABLE_TENNIS: 'Tênis de Mesa',
  BEACH_TENNIS: 'Beach Tênis',
};

export const SPORTS_MODALITIES_TENNIS_OPTIONS = [
  {
    key: '1',
    value: SPORTS_MODALITIES_TENNIS.TABLE_TENNIS,
    apiValue: 'TABLE_TENNIS',
  },
  {
    key: '2',
    value: SPORTS_MODALITIES_TENNIS.BEACH_TENNIS,
    apiValue: 'BEACH_TENNIS',
  },
];

export const SPORTS_MODALITIES_PADEL = {
  SINGLE_PADEL: 'Padel Simples',
  DOUBLE_PADEL: 'Padel Duplo',
};

export const SPORTS_MODALITIES_PADEL_OPTIONS = [
  {
    key: '1',
    value: SPORTS_MODALITIES_PADEL.SINGLE_PADEL,
    apiValue: 'SINGLE_PADEL',
  },
  {
    key: '2',
    value: SPORTS_MODALITIES_PADEL.DOUBLE_PADEL,
    apiValue: 'DOUBLE_PADEL',
  },
];

export const SPORTS_MODALITIES = {
  SOCCER: SPORTS_MODALITIES_SOCCER_OPTIONS,
  VOLLEYBALL: SPORTS_MODALITIES_VOLLEYBALL_OPTIONS,
  BASKETBALL: SPORTS_MODALITIES_BASKETBALL_OPTIONS,
  TENNIS: SPORTS_MODALITIES_TENNIS_OPTIONS,
  PADEL: SPORTS_MODALITIES_PADEL_OPTIONS,
};
