export const states = [
  { key: 'AC', label: 'Acre', value: 'AC' },
  { key: 'AL', label: 'Alagoas', value: 'AL' },
  { key: 'AP', label: 'Amapá', value: 'AP' },
  { key: 'AM', label: 'Amazonas', value: 'AM' },
  { key: 'BA', label: 'Bahia', value: 'BA' },
  { key: 'CE', label: 'Ceará', value: 'CE' },
  { key: 'DF', label: 'Distrito Federal', value: 'DF' },
  { key: 'ES', label: 'Espírito Santo', value: 'ES' },
  { key: 'GO', label: 'Goiás', value: 'GO' },
  { key: 'MA', label: 'Maranhão', value: 'MA' },
  { key: 'MT', label: 'Mato Grosso', value: 'MT' },
  { key: 'MS', label: 'Mato Grosso do Sul', value: 'MS' },
  { key: 'MG', label: 'Minas Gerais', value: 'MG' },
  { key: 'PA', label: 'Pará', value: 'PA' },
  { key: 'PB', label: 'Paraíba', value: 'PB' },
  { key: 'PR', label: 'Paraná', value: 'PR' },
  { key: 'PE', label: 'Pernambuco', value: 'PE' },
  { key: 'PI', label: 'Piauí', value: 'PI' },
  { key: 'RJ', label: 'Rio de Janeiro', value: 'RJ' },
  { key: 'RN', label: 'Rio Grande do Norte', value: 'RN' },
  { key: 'RS', label: 'Rio Grande do Sul', value: 'RS' },
  { key: 'RO', label: 'Rondônia', value: 'RO' },
  { key: 'RR', label: 'Roraima', value: 'RR' },
  { key: 'SC', label: 'Santa Catarina', value: 'SC' },
  { key: 'SP', label: 'São Paulo', value: 'SP' },
  { key: 'SE', label: 'Sergipe', value: 'SE' },
  { key: 'TO', label: 'Tocantins', value: 'TO' },
];
